sequenceDiagram
    participant Client as Клиент
    participant Auth as ms-auth
    participant DB

    Client->>Auth: POST /api/v1/register {credentials}
    activate Auth
    Auth->>Auth: Валидирует {credentials}
    alt {credentials} не валидны
    Auth-->>Client: Возвращает 400: неверный формат
    else {credentials} валидны
        Auth->>Auth: Хэширует пароль (bcrypt)
        Auth->>DB: INSERT INTO users (login, password) VALUES (?, ?)
        activate DB
        alt duplicate key error (login занят)
            DB-->>Auth: Ошибка дубликата
            Auth-->>Client: Возвращает 409: login занят
        else Другие ошибки БД
            DB -->> Auth: Ошибка БД
            Auth -->> Client: Возвращает 500: Внутренняя ошибка сервиса
        else вставка успешна
            Auth-->>Client: Возвращает 201: пользователь зарегистрирован
        end
        deactivate DB
    end
    deactivate Auth